# Generated by Django 5.2 on 2026-05-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_seed_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("ip_hash", models.CharField(max_length=64)),
            ],
            options={
                "unique_together": {("date", "ip_hash")},
            },
        ),
    ]
