# Generated by Django 5.2 on 2026-05-15 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(max_length=10)),
                (
                    "store_type",
                    models.CharField(
                        choices=[
                            ("accessories", "Accessories"),
                            ("clothing", "Clothing"),
                            ("jewelry", "Jewelry"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=3),
                ),
                ("reviews", models.IntegerField(default=0)),
                ("in_stock", models.BooleanField(default=True)),
                ("badge", models.CharField(blank=True, max_length=50, null=True)),
                ("color", models.CharField(default="#000000", max_length=20)),
                ("desc", models.TextField(blank=True)),
                ("variants", models.JSONField(default=list)),
                (
                    "store_type",
                    models.CharField(
                        choices=[
                            ("accessories", "Accessories"),
                            ("clothing", "Clothing"),
                            ("jewelry", "Jewelry"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="store.category",
                    ),
                ),
            ],
        ),
    ]
